### ISSUE TITLE
How can I limit or disable query type?

### ISSUE THREAD

**Issue by garrriton** [m13253/dns-over-https#113]
Situation:

- I want to configure doh-server to query only A record and block(ignore) other query type like AAAA.
- upsteam DNS server has ad-blocking capability and your server is returning AAAA record, rendering adblock useless.

e.g

advert.com A 0.0.0.0 (same answer from upsteam)
advert.com AAAA 111.2222.333...4444

---

Please add a `limit (block by query type)` or `select upsteam by query type` doh-server.conf options.

-  `limit (block by query type)` 
limit_type = 

default:none. values are uppercase comma-separated. sample values: limit_type = A,TXT will only allow A or TXT queries and return empty{} results if other types are asked.

- `select upsteam by query type`

upsteam = [
 "udp:1.1.1.1:53",
 "A@udp:1.0.0.1:53",
 "AAAA@udp:8.8.8.8:53"
]

**Comment by garrriton** [comment]
If the 2nd option is selected I could use upsteam= [... "AAAA@udp:127.0.0.1:1234"] to block any AAAA requests (request goes into empty location)

Which code line I should modify to block AAAA now?

**Comment by m13253** [comment]
I believe this is a problem with your upstream ad blocker. It should also replace `AAAA` record with `::` in addition to `A`. This problem would also affect users that do not use DoH, so why not report to them?

But the most simple workaround to you is just disable IPv6 from your computer, since banning `AAAA` records is essentially equal to disabling IPv6, because almost no software connects to hard-coded IPv6 address.

**Comment by gdm85** [comment]
> * I want to configure doh-server to query only A record and block(ignore) other query type like AAAA.

What would be the behaviour when such records are received? not found?



> I believe this is a problem with your upstream ad blocker. It should also replace `AAAA` record with `::` in addition to `A`. This problem would also affect users that do not use DoH, so why not report to them?

@garrriton did you report this issue upstream?



> the most simple workaround to you is just disable IPv6 from your computer, since banning `AAAA` records essentially equals to disabling IPv6, because almost no software connects to hard-coded IPv6 address.

There are some configuration where it would be beneficial, like for example disabling IPv6 on a single interface, but I don't think that other software/libraries would play nicely.

**Comment by m13253** [comment]
I prefer to close this issue because DNS filtering is generally done by another software.
I personally want to include only features that must be implemented at DoH layer. (For example, ECS must be implemented at this layer to correctly track X-Forwarded-For headers.)
As long as there is an external software to perform a specific task, I would rather let them do the task.
