### ISSUE TITLE
Request support for configuration of ednsClientAddress and ednsClientNetmask

### ISSUE THREAD

**Issue by Phuker** [m13253/dns-over-https#32]
The code works good, but findClientIP() can't always get the correct edns client subnet address. Can we configure them in doh-client.conf ?
Thank you!

**Comment by m13253** [comment]
(Duplicate in #17.)

This is a repeated requested feature. Since you requested this, I am considering this again.

It is not difficult to implement (and we already have working code), but I am afraid of any side-effects caused by the inclusion of this feature: If every user is submitting fake ECS data, I am afraid DNS providers will consider ECS untrustworthy, thus stop reading ECS from clients. (In fact Google's 8.8.8.8 already stopped reading ECS from clients some years ago.)

Additionally, very few recursive DNS resolvers now use ECS data from clients. They either override the ECS data (Google DNS), or completely remove the ECS data (Cloudflare DNS).

Therefore, I think a fixed ECS feature may not be able to solve the problem. It only works if you don't rely on public recursive DNS resolvers including Google DNS or Cloudflare DNS. But If you already have an independent DNS infrastructure, you must have better methods to handle ECS (for example, using dnsdist or BIND).

**Comment by Phuker** [comment]
I read your reply and #17, and now I realized that DNS and DNS in my country is really a complicated problem.
I live in China, and there is DNS pollution, GFW, even maybe DNS monitoring here. So I want to build up a DNS server in my office to solve these problems. I can't access https://dns.google.com/resolve directly, then I configured apache and set up a reverse proxy on my VPS, but some CDN can't be resolved properly. Then I found that custom ECS is not supported in this project.
I want to keep things simple, so I edited some code of this project just like lightsing in #17 have done, and now every thing works fine.
These are what i have experienced recently, and I think this feature is useful and a simple solution in some cases. Thank you very much!

**Comment by m13253** [comment]
You can try to run a pair of doh-server and doh-client on your VPS.

The doh-server + apache connects to your computer. And doh-client connects to https://dns.google.com/experimental (Note: "experimental").

This will detect and submit ECS data correctly. I have tested that it works.

**Comment by Phuker** [comment]
Oh I understand, using a pair of doh-server and doh-client on my VPS maybe a good way to detect ECS data automatically.
But in my office, maybe I will keep my version of code running for the moment, as it is working fine and I want to keep things simple.
Maybe I will try your advice in some situations later (i.e. taking a mobile device here and there without re-configuring ECS data manually).
Thank you!

**Comment by m13253** [comment]
I'm happy that the problem is solved!

P.S. The "fix ECS" feature will probably not be added in hear future, for the health of the Internet. (Once service providers misconfigure their server to send fixed ECS, other providers will stop reading ECS instructions, eventally rendering it useless.)

**Comment by m13253** [comment]
Maybe solved with #92
