### ISSUE TITLE
post queries?

### ISSUE THREAD

**Issue by srayneau** [m13253/dns-over-https#60]
Hello,
Is it possible to do post queries instead of get?

**Comment by m13253** [comment]
POST queries is supported on both doh-client and doh-server.
Doh-client will automatically use POST when the request is too long. But doh-client does not use POST when the request is short.

Some people argue that POST is better for privacy since most server does not log POST queries by default. However it does not prevent evil servers that deliberately logs all queries. Therefore user should use a server with no-log policy instead of relying on POST.

Considering the benefit of providing cache through GET, I recommend using GET for short queries, and switch to POST for long queries.

**Comment by srayneau** [comment]
In my company doh queries do not work in get with base64 content.
Is it possible to force the post for doh-client?

**Comment by m13253** [comment]
> In my company doh queries do not work in get with base64 content.
> Is it possible to force the post for doh-client?

That's possible. Find the following line:
```go
if len(requestURL) < 2048 {
```
Change it to:
```
if len(requestURL) < 0 {
```
and that should force the use of POST method.

**Comment by srayneau** [comment]
thanks a lot for your help
