### ISSUE TITLE
More narrow Access-Control-Allow-Methods ?

### ISSUE THREAD

**Issue by mdavids** [m13253/dns-over-https#62]
I was wondering; wouldn't a POST, GET be sufficient here?

https://github.com/m13253/dns-over-https/blob/master/doh-server/server.go#L140

Also, why adding this header in the first place? Shouldn't the webserver take care of this?

**Comment by m13253** [comment]
OPTION is useful for the real original motivation of inventing this software -- to allow JavaScript application to do DNS query using JSON. This software was invented way before the IETF protocol, so privacy-related features were added afterwards.

HEAD is useful for caching. But I'm not sure whether my server really supports HEAD. And I'm also not sure whether disabling HEAD will have any good or bad impacts.

And of course, you can configure the frontend webserver to override this header. And you can submit pull request to me if you can make it more secure and better.

**Comment by m13253** [comment]
I am asking for further advice about this issue.

I enable OPTION by default because DoH is invented originally for web apps.
If you established a public DoH server and forget to enable OPTION, then this server will be unreachable for web apps and you will hardly notice it.
Contrary, if you have a private DoH server and forget to disable OPTION, then your server will only have more requests from web apps and you will easily notice it if anything wrong happens.
Additionally, enabling or disabling OPTION only affects web app clients, not standalone clients. If you don't want to serve clients from other domains, disabling OPTION will not work because the majority of the users are using standalone clients now.

Therefore, this is why I enable OPTION by default. You can always override this behavior in your load balancer server.

If you don't have further comments, you may choose to close this issue.
