### ISSUE TITLE
Feature Request: Allows specify the CIDR used for ECS in config

### ISSUE THREAD

**Issue by ZeroClover** [m13253/dns-over-https#80]
It is a good idea to use /24 CIDR for privacy, but some upstream DNS only accept /32 ECS (such as Tencent DNS).

It is better to use /24 by default and use other CIDR subnets in the configuration file to specify someone's needs.

**Comment by m13253** [comment]
This is a good idea.
I will come back and implement this feature.

Meanwhile, you can search the source code and replace 24 into 32.

**Comment by SurfaceBook2** [comment]
By the way, can you add an option to the config file to use a custom global IP list?
Or just add an option to disable global IP checking altogether.

**Comment by m13253** [comment]
> By the way, can you add an option to the config file to use a custom global IP list?
> Or just add an option to disable global IP checking altogether.

I don't think this is useful, because it is not meaningful for the server to know that your IP is 192.168.1.1.

**Comment by m13253** [comment]
I would like to acquire more information on this: Are you talking about doh-server or doh-client?

If doh-client, I will be able to implement this feature.
If doh-server, I would prefer to leave as is, which is /24 for IPv4 and /48 for IPv6. Here is my reason:

Even though people can patch the source code and force a /32 ECS, if I made this setting easily configurable, when server admins face a cache issue relating to ECS (which is very common. Even Google and Alibaba DNS had this problem in the past), instead of fixing their cache program to solve the issue, they might simply configure a /32 ECS if it can also solve the problem, which can be--you know--very dangerous.

Most server admins are not familiar with BGP stuff (and even the authors of RFC 7871 aren't!). Many admins may have the misconception of “/28 is more precise than /24”. But in fact, /28 has the same geographic resolution as /24 because top tier ISPs only accept /24 announcements. Even though small ISPs may accept /28 announcements, those /24 announcements determine your latency to most parts of the world.
Similarly, RFC 7871 suggests /56 for IPv6, even some productive DNS servers are preconfigured as so. However, top tier ISPs only accept /48 for IPv6, and /56 is precise enough to track to your door. That's why I am hard-coding my software as /24 and /48. I don't want users to configure it to /56 because we shouldn't believe the RFC in this topic.

**Comment by ZeroClover** [comment]
Hi,

We operate AS64271 and are not ignorant of BGP. Our network supports the operation of NextDNS Anycast in Asia. I also don't understand any substantial relationship between ECS and BGP. Our backbone network can route every IP address in /24 IPv4 to different regions, just like 162.14.21.178 (Tencent Cloud AIA for Tencent DoH).

Allowing a custom subnet size is not an "**accuracy**" issue, but the upstream DNS **only** accepts /32 CIDR.

The only Public DNS that accepts ECS in Mainland China is Tencent DNS. Alibaba DNS does not really support ECS.

We already have other ways to solve this problem, and I’m sorry for the trouble.

**Comment by m13253** [comment]
> We operate AS64271 and are not ignorant of BGP.

I am sorry for possible misunderstandings or offenses. And I appreciate your effort in providing free, open, and private Internet access.
In fact, I am complaining about Tencent's admins: they are the ones who simply enables /32 to solve a cache problem at their side. Maybe I will try to reach Tencent's technicians for this problem.

Please forgive my stubborn on ECS's topic: this topic is also addressed in #32, #73, and I was not really convinced to change my mid (in the near future).

**Comment by m13253** [comment]
Solved with #92
